### ISSUE TITLE
Server crash: Exception ticking world

### ISSUE THREAD

**Issue by RisingInIris2017** [Shinoow/The-Beneath#23]
#### Description:
I installed The Beneath Mod on my server.
My server has crashed for several times with nearly the same crash-reports, as I attached below.
All those reports says "DIM10" is generating exception, which is the Beneath dimension.
So I think posting this issue here is helpful.

#### Crash report:
https://paste.ubuntu.com/p/HPwnfzsNHH/
https://paste.ubuntu.com/p/hPjhn2w6fD/
https://paste.ubuntu.com/p/fyJhX7f72V/

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- The Beneath: 1.7.0

#### Latest log file for when the issue was present:
https://gist.github.com/RisingInIris2017/5224493f7288009a3a4fc2ad2718a063

Sorry for non-English characters in all of my logs attached.
I am running a server in a non-English country, so there are such characters.
Not mean to bother you with that. Sorry again.

Thanks for your kindhearted help in advance.

**Comment by Shinoow** [comment]
Do you have any logs containing whatever content there might be there prior to the crashing happening? The log file you posted only contains the initialization, which I can't find any information to identify the cause from.
The only thing I can find in the crash reports is it happens during world ticking, but nothing points towards any specific code that would indicate what is triggering the crash.
Do you get the same crashes if you run the server without bukkit and/or any of the installed plugins?

**Comment by RisingInIris2017** [comment]
> Do you have any logs containing whatever content there might be there prior to the crashing happening?

Yes, I have checked the log before the crash occurred, and find these lines:

[20:32:51] [Server thread/DEBUG] [FML]: Queueing dimension 10 to unload
[20:32:51] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.world.WorldServer = oo = jar:file:/C:/MARYT-Servers/MARYT_9th/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/oo.class
[20:32:51] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.server.MinecraftServer = net.minecraft.server.MinecraftServer = jar:file:/C:/MARYT-Servers/MARYT_9th/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/net/minecraft/server/MinecraftServer.class
[20:32:51] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.server.dedicated.DedicatedServer = nz = jar:file:/C:/MARYT-Servers/MARYT_9th/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar!/nz.class
[20:32:51] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: java.lang.Thread = java.lang.Thread = jar:file:/C:/Program%20Files/j2sdk-image/jre/lib/rt.jar!/java/lang/Thread.class
[20:32:51] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: 
java.lang.NullPointerException: null
	at net.minecraft.world.WorldServer.tick(WorldServer.java:457) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:885) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:466) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:775) [?:1.8.0_242]
[20:32:51] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Crash report is saved to：C:\MARYT-Servers\MARYT_9th\.\crash-reports\crash-2020-07-15_20.32.51-server.txt
[20:32:51] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Server shutting down

These lines come from [this log](https://gist.github.com/RisingInIris2017/75e29232f62a49b14a3762da3227fec6), Line 36613 - Line 36627.
I have not tested this issue on non-bukkit server platform, due to I did not know how to reproduce it, too.
